import { MAX_FAMILY_MEMBERS, MIN_FAMILY_MEMBERS } from "../components/upload-flow.constants";
import type { FamilyMember } from "../components/upload-flow.types";

export type FamilyMemberUpdate = Partial<FamilyMember> | ((member: FamilyMember) => Partial<FamilyMember>);
export type FamilyUploadState = { members: FamilyMember[]; activeIndex: number; countInput: string };
export type FamilyUploadEvent =
  | { type: "selected"; index: number }
  | { type: "count-edited"; input: string; candidates: FamilyMember[] }
  | { type: "count-normalized"; candidates: FamilyMember[] }
  | { type: "member-updated"; index: number; update: FamilyMemberUpdate };

/** Pure transitions retain each existing member's upload credential and saved result. */
export function familyUploadReducer(state: FamilyUploadState, event: FamilyUploadEvent): FamilyUploadState {
  if (event.type === "selected") {
    return event.index >= 0 && event.index < state.members.length
      ? { ...state, activeIndex: event.index } : state;
  }
  if (event.type === "member-updated") {
    return {
      ...state, members: state.members.map((member, index) => index === event.index
        ? { ...member, ...(typeof event.update === "function" ? event.update(member) : event.update) }
        : member)
    };
  }
  const input = event.type === "count-edited" ? event.input : state.countInput;
  if (!/^\d*$/.test(input)) return state;
  const entered = Number(input);
  if (event.type === "count-edited" && (!input || entered < MIN_FAMILY_MEMBERS || entered > MAX_FAMILY_MEMBERS)) {
    return { ...state, countInput: input };
  }
  const count = Math.max(MIN_FAMILY_MEMBERS, Math.min(MAX_FAMILY_MEMBERS, entered));
  const members = Array.from({ length: count }, (_, index) => state.members[index] ?? event.candidates[index]);
  // Candidate IDs are generated by the event producer, never inside the reducer.
  if (members.some((member) => !member)) return state;
  return {
    members: members.map((member, index) => index === 0 ? { ...member, relation: "Head" } : member),
    countInput: String(count), activeIndex: Math.min(state.activeIndex, count - 1)
  };
}
