"""Typed document-assignment review exports with current group authority."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated, Any
from uuid import UUID

from fastapi import FastAPI, HTTPException
from mcp.server import MCPServer
from mcp.server.auth.middleware.auth_context import get_access_token
from mcp.types import ToolAnnotations
from pydantic import Field, ValidationError

from app.application.mcp.artifacts import ArtifactError, MCPArtifactService
from app.application.mcp.credentials import MCPAuthError
from app.application.mcp.document_export_source import DocumentExcelSupport
from app.application.mcp.document_exports import (
    DocumentExportRequest,
    MCPDocumentExportService,
    document_export_operation,
)
from app.application.mcp.operations import MCPOperationError, MCPOperationService
from app.core.config.settings import Settings
from app.infrastructure.repositories.audit_log_repository import AuditLogRepository, AuditResult
from app.presentation.api.v1.routes.document_distribution_responses import (
    _document_response_snapshot,
)
from app.presentation.api.v1.routes.document_distribution_review_support import (
    _document_assignment_export_rows,
    _passenger_review_rows,
    _safe_filename,
)
from app.presentation.api.v1.routes.document_distribution_scope import _group_passengers
from app.presentation.mcp.invocation import invoke_operation, mark_invocation_audited


def document_excel_support() -> DocumentExcelSupport:
    return DocumentExcelSupport(
        passengers=_group_passengers,
        document_response=_document_response_snapshot,
        review_rows=_passenger_review_rows,
        export_rows=_document_assignment_export_rows,
        filename=_safe_filename,
    )


async def _invoke_export(
    app: FastAPI,
    settings: Settings,
    *,
    name: str,
    request: DocumentExportRequest | None = None,
    operation_id: UUID | None = None,
) -> dict[str, Any]:
    token = get_access_token()
    principal = None
    outcome: AuditResult
    async with app.state.mcp_session_factory() as session:
        try:
            if token is None:
                raise MCPAuthError("invalid_token", 401)
            artifacts = MCPArtifactService(
                session, settings, storage=getattr(app.state, "mcp_artifact_storage", None)
            )
            service = MCPDocumentExportService(
                session, settings, document_excel_support(), artifacts=artifacts
            )
            if request is not None:
                principal = await MCPOperationService(session, settings)._authorize(
                    token.token, "mcp:export", tool_name=name
                )
                result = await service.inspect(principal, request)
            else:
                assert operation_id is not None
                result = await service.generate(access_token=token.token, operation_id=operation_id)
            outcome = "success"
        except MCPAuthError:
            await session.rollback()
            outcome = "denied"
            result = {
                "error": "access_denied",
                "message": "The connection no longer authorizes this export.",
            }
        except (
            ArtifactError,
            MCPOperationError,
            HTTPException,
            ValidationError,
        ) as exc:
            await session.rollback()
            outcome = "blocked"
            result = {
                "error": "export_revision_changed"
                if isinstance(exc, MCPOperationError) and exc.code == "export_revision_changed"
                else "export_unavailable",
                "message": "Inspect the current selection, fields and revision. Expired completed exports cannot be regenerated by retrying the same operation.",
            }
            if isinstance(exc, ArtifactError) and exc.status_code == 503:
                result = {
                    "error": "export_busy",
                    "message": "Export sources or generation capacity are busy. Resume the same operation ID later; keep its original retry key.",
                }
        except Exception:
            await session.rollback()
            outcome = "failed"
            result = {
                "error": "export_failed",
                "message": "Inspect the saved operation before retrying with its operation ID. A new retry key may create another intended export.",
            }
        claims = token.claims if token and token.claims else {}
        audit = await AuditLogRepository(session).record(
            action=f"mcp.tool.{name}",
            entity_type="mcp_operation",
            entity_id=str(operation_id) if operation_id else None,
            user_id=UUID(token.subject) if token and token.subject else None,
            result=outcome,
            metadata={"capability": "mcp:export", "connection_id": claims.get("grant_id")},
        )
        # The durable completion and its safe invocation audit become visible together.
        await session.commit()
        mark_invocation_audited()
        result.update(
            audit_id=str(audit.id),
            environment=settings.app_env,
            revision=settings.app_revision,
            observed_at=datetime.now(UTC).isoformat(),
            completeness="complete" if outcome == "success" else "unavailable",
        )
        if operation_id is not None:
            result.setdefault("operation_id", str(operation_id))
        return result


def register_document_assignment_export_tools(
    server: MCPServer, app: FastAPI, settings: Settings
) -> None:
    definition = document_export_operation(settings, document_excel_support())
    app.state.mcp_operations[definition.policy.name] = definition

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=True, destructive_hint=False, idempotent_hint=True, open_world_hint=False
        ),
    )
    async def inspect_document_assignment_export(export: DocumentExportRequest) -> dict[str, Any]:
        """Inspect document assignment review rows for exact agency/group/type IDs.

        Choose all, assigned, missing, sent, not_sent or multiple_pdfs, with an
        optional passenger-name search. Reads the website's retained assignment
        and delivery review; does not assign, approve, save or send documents.
        The file contains review metadata, not document PDFs or download URLs.
        Oversized scopes are rejected without producing a partial workbook.
        """
        return await _invoke_export(
            app, settings, name="inspect_document_assignment_export", request=export
        )

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    async def prepare_document_assignment_export(
        export: DocumentExportRequest,
        expected_revision: Annotated[str, Field(pattern=r"^[a-f0-9]{64}$")],
        idempotency_key: Annotated[str, Field(min_length=16, max_length=256)],
    ) -> dict[str, Any]:
        """Prepare the inspected assignment review using one stable retry key.

        A committed request receipt precedes generation of a private expiring
        spreadsheet. Retry an identical request with its original key after an
        uncertain response, or resume its saved operation ID. Local delivery
        verifies checksum and size; no assignment, history or message is changed.
        """
        receipt = await invoke_operation(
            app,
            settings,
            definition,
            idempotency_key=idempotency_key,
            payload={
                "export": export.model_dump(mode="json"),
                "expected_revision": expected_revision,
            },
        )
        if "receipt" not in receipt:
            return receipt
        operation_id = UUID(receipt["receipt"]["operation_id"])
        result = await _invoke_export(
            app, settings, name="generate_document_assignment_export", operation_id=operation_id
        )
        result["receipt"] = receipt["receipt"]
        return result

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    async def resume_document_assignment_export(operation_id: UUID) -> dict[str, Any]:
        """Resume one queued export or recover its unexpired completed artifact.

        Current actor, export capability and exact group association are
        revalidated. A new authorized connection receives its own protected
        locator to the same workbook. Expired results never regenerate.
        """
        return await _invoke_export(
            app, settings, name="resume_document_assignment_export", operation_id=operation_id
        )
