"""Typed, audited Excel inspection, durable preparation and explicit recovery."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated, Any
from uuid import UUID

from fastapi import FastAPI, HTTPException
from mcp.server import MCPServer
from mcp.server.auth.middleware.auth_context import get_access_token
from mcp.types import ToolAnnotations
from pydantic import Field, ValidationError

from app.application.mcp.artifacts import ArtifactError, MCPArtifactService
from app.application.mcp.credentials import MCPAuthError
from app.application.mcp.exports import (
    ExcelExportRequest,
    MCPExcelExportService,
    MCPExcelSupport,
    excel_export_operation,
)
from app.application.mcp.operations import MCPOperationError, MCPOperationService
from app.application.use_cases.passports.prepare_group_excel import ExcelPreparationError
from app.core.config.settings import Settings
from app.core.logging.logger import get_logger
from app.infrastructure.repositories.audit_log_repository import AuditLogRepository, AuditResult
from app.presentation.api.v1.routes.passport_routes.excel_exports import group_excel_support
from app.presentation.api.v1.routes.passport_routes.selected_exports import selected_excel_support
from app.presentation.mcp.invocation import invoke_operation, mark_invocation_audited

logger = get_logger(__name__)


def excel_support() -> MCPExcelSupport:
    return MCPExcelSupport(group_excel_support(), selected_excel_support())


async def _invoke_export(
    app: FastAPI,
    settings: Settings,
    *,
    name: str,
    request: ExcelExportRequest | None = None,
    operation_id: UUID | None = None,
) -> dict[str, Any]:
    token = get_access_token()
    principal = None
    outcome: AuditResult
    async with app.state.mcp_session_factory() as session:
        try:
            if token is None:
                raise MCPAuthError("invalid_token", 401)
            artifacts = MCPArtifactService(
                session, settings, storage=getattr(app.state, "mcp_artifact_storage", None)
            )
            service = MCPExcelExportService(session, settings, excel_support(), artifacts=artifacts)
            if request is not None:
                principal = await MCPOperationService(session, settings)._authorize(
                    token.token, "mcp:export"
                )
                result = await service.inspect(principal, request)
            else:
                assert operation_id is not None
                result = await service.generate(access_token=token.token, operation_id=operation_id)
            outcome = "success"
        except MCPAuthError:
            await session.rollback()
            outcome = "denied"
            result = {
                "error": "access_denied",
                "message": "The connection no longer authorizes this export.",
            }
        except (
            ArtifactError,
            MCPOperationError,
            ExcelPreparationError,
            HTTPException,
            ValidationError,
        ) as exc:
            await session.rollback()
            outcome = "blocked"
            result = {
                "error": "export_revision_changed"
                if isinstance(exc, MCPOperationError) and exc.code == "export_revision_changed"
                else "export_unavailable",
                "message": "Inspect the current selection, fields and revision. Expired completed exports cannot be regenerated by retrying the same operation.",
            }
            if isinstance(exc, ArtifactError) and exc.status_code == 503:
                result = {
                    "error": "export_busy",
                    "message": "Export sources or generation capacity are busy. Resume the same operation ID later; keep its original retry key.",
                }
        except Exception as exc:
            cause = exc.__cause__ or (None if exc.__suppress_context__ else exc.__context__)
            # Exception text/tracebacks can contain storage keys, signed URLs,
            # credentials or source records. Keep diagnostics to types and IDs.
            logger.error(
                "mcp_excel_export_failed",
                operation_id=str(operation_id) if operation_id else None,
                tool_name=name,
                error_type=type(exc).__name__,
                cause_type=type(cause).__name__ if cause is not None else None,
            )
            await session.rollback()
            outcome = "failed"
            result = {
                "error": "export_failed",
                "message": "Inspect the saved operation before retrying with its operation ID. A new retry key may create another intended export.",
            }
        claims = token.claims if token and token.claims else {}
        audit = await AuditLogRepository(session).record(
            action=f"mcp.tool.{name}",
            entity_type="mcp_operation",
            entity_id=str(operation_id) if operation_id else None,
            user_id=UUID(token.subject) if token and token.subject else None,
            result=outcome,
            metadata={"capability": "mcp:export", "connection_id": claims.get("grant_id")},
        )
        # The durable completion and its safe invocation audit become visible together.
        await session.commit()
        mark_invocation_audited()
        result.update(
            audit_id=str(audit.id),
            environment=settings.app_env,
            revision=settings.app_revision,
            observed_at=datetime.now(UTC).isoformat(),
            completeness="complete" if outcome == "success" else "unavailable",
        )
        if operation_id is not None:
            result.setdefault("operation_id", str(operation_id))
        return result


def register_export_tools(server: MCPServer, app: FastAPI, settings: Settings) -> None:
    definition = excel_export_operation(settings, excel_support())
    app.state.mcp_operations[definition.policy.name] = definition

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=True, destructive_hint=False, idempotent_hint=True, open_world_hint=False
        ),
    )
    async def inspect_excel_export(export: ExcelExportRequest) -> dict[str, Any]:
        """Inspect exact agency/group/passport IDs and return export options and a revision.

        Resolve ambiguous selections before proceeding. Group exports support all
        or incremental after a completed baseline; selected exports use all only.
        Pending WhatsApp recipients and selected supplemental fields follow website
        rules. This inspection creates no workbook or history checkpoint.
        """
        return await _invoke_export(app, settings, name="inspect_excel_export", request=export)

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    async def prepare_excel_export(
        export: ExcelExportRequest,
        expected_revision: Annotated[str, Field(pattern=r"^[a-f0-9]{64}$")],
        idempotency_key: Annotated[str, Field(min_length=16, max_length=256)],
    ) -> dict[str, Any]:
        """Prepare an Excel workbook from the inspected revision and one stable retry key.

        A committed request receipt precedes generation. Retry the identical request
        with the same key after an uncertain response, or resume its operation ID.
        This writes a private expiring copy; it never changes passport data. Group
        history completes only after checksum-verified local delivery acknowledgement.
        Selected exports intentionally have no incremental history checkpoint.
        """
        receipt = await invoke_operation(
            app,
            settings,
            definition,
            idempotency_key=idempotency_key,
            payload={
                "export": export.model_dump(mode="json"),
                "expected_revision": expected_revision,
            },
        )
        if "receipt" not in receipt:
            return receipt
        operation_id = UUID(receipt["receipt"]["operation_id"])
        result = await _invoke_export(
            app, settings, name="generate_excel_export", operation_id=operation_id
        )
        result["receipt"] = receipt["receipt"]
        return result

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    async def resume_excel_export(operation_id: UUID) -> dict[str, Any]:
        """Resume one queued export or recover its unexpired completed artifact.

        Current actor, connection capability, every original group and the retained
        checkpoint are revalidated. A new connection receives its own protected
        locator to the same workbook/history. Expired results never regenerate.
        """
        return await _invoke_export(
            app, settings, name="resume_excel_export", operation_id=operation_id
        )
