"""Typed image ZIP inspection, durable preparation and protected recovery."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated, Any
from uuid import UUID

from fastapi import FastAPI, HTTPException
from mcp.server import MCPServer
from mcp.server.auth.middleware.auth_context import get_access_token
from mcp.types import ToolAnnotations
from pydantic import Field, ValidationError
from sqlalchemy.exc import DBAPIError

from app.application.mcp.artifacts import ArtifactError, MCPArtifactService
from app.application.mcp.credentials import MCPAuthError
from app.application.mcp.image_exports import (
    ImageExportRequest,
    MCPImageExportService,
    image_export_operation,
)
from app.application.mcp.operations import MCPOperationError, MCPOperationService
from app.application.use_cases.passports.prepare_image_export import ImagePreparationError
from app.core.config.settings import Settings
from app.infrastructure.export.passport_image_zip_exporter import PassportImageExportError
from app.infrastructure.imaging.passport_image_cropper import PassportImageCropError
from app.infrastructure.repositories.audit_log_repository import AuditLogRepository, AuditResult
from app.presentation.api.v1.routes.document_distribution_match_source import (
    _read_linked_document_match_source,
)
from app.presentation.api.v1.routes.passport_routes.image_exports import image_export_support
from app.presentation.mcp.invocation import invoke_operation, mark_invocation_audited


async def _invoke_export(
    app: FastAPI,
    settings: Settings,
    *,
    name: str,
    request: ImageExportRequest | None = None,
    operation_id: UUID | None = None,
) -> dict[str, Any]:
    token = get_access_token()
    principal = None
    outcome: AuditResult
    async with app.state.mcp_session_factory() as session:
        try:
            if token is None:
                raise MCPAuthError("invalid_token", 401)
            artifacts = MCPArtifactService(
                session, settings, storage=getattr(app.state, "mcp_artifact_storage", None)
            )
            service = MCPImageExportService(
                session,
                settings,
                image_export_support(),
                artifacts=artifacts,
                linked_source=_read_linked_document_match_source,
                image_storage=getattr(app.state, "mcp_image_storage", None),
            )
            if request is not None:
                principal = await MCPOperationService(session, settings)._authorize(
                    token.token, "mcp:export", tool_name=name
                )
                result = await service.inspect(principal, request)
            else:
                assert operation_id is not None
                result = await service.generate(access_token=token.token, operation_id=operation_id)
            outcome = "success"
        except MCPAuthError:
            await session.rollback()
            outcome = "denied"
            result = {
                "error": "access_denied",
                "message": "The connection no longer authorizes this export.",
            }
        except (
            ArtifactError,
            MCPOperationError,
            ImagePreparationError,
            PassportImageExportError,
            PassportImageCropError,
            DBAPIError,
            HTTPException,
            ValidationError,
        ) as exc:
            await session.rollback()
            outcome = "blocked"
            result = {
                "error": "export_revision_changed"
                if isinstance(exc, MCPOperationError) and exc.code == "export_revision_changed"
                else "export_unavailable",
                "message": "Inspect the current selection, fields and revision. Expired completed exports cannot be regenerated by retrying the same operation.",
            }
            if (
                (isinstance(exc, ArtifactError) and exc.status_code == 503)
                or isinstance(exc, DBAPIError)
                and getattr(exc.orig, "sqlstate", None) == "55P03"
            ):
                result = {
                    "error": "export_busy",
                    "message": "Export sources or generation capacity are busy. Resume the same operation ID later; keep its original retry key.",
                }
        except Exception:
            await session.rollback()
            outcome = "failed"
            result = {
                "error": "export_failed",
                "message": "Inspect the saved operation before retrying with its operation ID. A new retry key may create another intended export.",
            }
        claims = token.claims if token and token.claims else {}
        audit = await AuditLogRepository(session).record(
            action=f"mcp.tool.{name}",
            entity_type="mcp_operation",
            entity_id=str(operation_id) if operation_id else None,
            user_id=UUID(token.subject) if token and token.subject else None,
            result=outcome,
            metadata={"capability": "mcp:export", "connection_id": claims.get("grant_id")},
        )
        # The durable completion and its safe invocation audit become visible together.
        await session.commit()
        mark_invocation_audited()
        result.update(
            audit_id=str(audit.id),
            environment=settings.app_env,
            revision=settings.app_revision,
            observed_at=datetime.now(UTC).isoformat(),
            completeness="complete" if outcome == "success" else "unavailable",
        )
        if operation_id is not None:
            result.setdefault("operation_id", str(operation_id))
        return result


def register_image_export_tools(server: MCPServer, app: FastAPI, settings: Settings) -> None:
    definition = image_export_operation(
        settings, image_export_support(), linked_source=_read_linked_document_match_source
    )
    app.state.mcp_operations[definition.policy.name] = definition

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=True, destructive_hint=False, idempotent_hint=True, open_world_hint=False
        ),
    )
    async def inspect_image_export(export: ImageExportRequest) -> dict[str, Any]:
        """Inspect current cropped passport images for one exact agency and group.

        Supports all/incremental group exports, or up to 500 exact selected
        passports. Naming uses the complete group, current zones and saved crops.
        Returns the revision and size limits before any storage read or ZIP write.
        """
        return await _invoke_export(app, settings, name="inspect_image_export", request=export)

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    async def prepare_image_export(
        export: ImageExportRequest,
        expected_revision: Annotated[str, Field(pattern=r"^[a-f0-9]{64}$")],
        idempotency_key: Annotated[str, Field(min_length=16, max_length=256)],
    ) -> dict[str, Any]:
        """Prepare a protected ZIP with one stable retry key and inspected revision.

        Originals and saved edits remain unchanged. This first commits a durable
        request, then reads only its database-prepared image keys and packages the
        canonical effective images. Export history completes only after verified
        local delivery acknowledgement. Selected-image exports have no baseline.
        """
        receipt = await invoke_operation(
            app,
            settings,
            definition,
            idempotency_key=idempotency_key,
            payload={
                "export": export.model_dump(mode="json"),
                "expected_revision": expected_revision,
            },
        )
        if "receipt" not in receipt:
            return receipt
        operation_id = UUID(receipt["receipt"]["operation_id"])
        result = await _invoke_export(
            app, settings, name="generate_image_export", operation_id=operation_id
        )
        result["receipt"] = receipt["receipt"]
        return result

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    async def resume_image_export(operation_id: UUID) -> dict[str, Any]:
        """Resume the exact image generation operation or recover its protected ZIP.

        Current authority and group scope are checked before recovery. The same
        actor may recover through a new authorized connection. An expired
        successful result is never rebuilt by retrying this operation.
        """
        return await _invoke_export(
            app, settings, name="resume_image_export", operation_id=operation_id
        )
