"""Typed hotel XLSX preparation and recovery; no allocation or check-in changes."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated, Any
from uuid import UUID

from fastapi import FastAPI, HTTPException
from mcp.server import MCPServer
from mcp.server.auth.middleware.auth_context import get_access_token
from mcp.types import ToolAnnotations
from pydantic import Field, ValidationError

from app.application.mcp.artifacts import ArtifactError, MCPArtifactService
from app.application.mcp.credentials import MCPAuthError
from app.application.mcp.operations import MCPOperationError, MCPOperationService
from app.application.mcp.rooming_exports import (
    MCPRoomingExportService,
    RoomingExportRequest,
    rooming_export_operation,
)
from app.application.use_cases.rooming.prepare_excel import RoomingPreparationError
from app.core.config.settings import Settings
from app.infrastructure.repositories.audit_log_repository import AuditLogRepository, AuditResult
from app.presentation.api.v1.routes.rooming import rooming_excel_support
from app.presentation.mcp.invocation import invoke_operation, mark_invocation_audited


async def _invoke_export(
    app: FastAPI,
    settings: Settings,
    *,
    name: str,
    request: RoomingExportRequest | None = None,
    operation_id: UUID | None = None,
) -> dict[str, Any]:
    token = get_access_token()
    principal = None
    outcome: AuditResult
    async with app.state.mcp_session_factory() as session:
        try:
            if token is None:
                raise MCPAuthError("invalid_token", 401)
            artifacts = MCPArtifactService(
                session, settings, storage=getattr(app.state, "mcp_artifact_storage", None)
            )
            service = MCPRoomingExportService(
                session, settings, rooming_excel_support(), artifacts=artifacts
            )
            if request is not None:
                principal = await MCPOperationService(session, settings)._authorize(
                    token.token, "mcp:export"
                )
                result = await service.inspect(principal, request)
            else:
                assert operation_id is not None
                result = await service.generate(access_token=token.token, operation_id=operation_id)
            outcome = "success"
        except MCPAuthError:
            await session.rollback()
            outcome = "denied"
            result = {
                "error": "access_denied",
                "message": "The connection no longer authorizes this export.",
            }
        except (
            ArtifactError,
            MCPOperationError,
            RoomingPreparationError,
            HTTPException,
            ValidationError,
        ) as exc:
            await session.rollback()
            outcome = "blocked"
            result = {
                "error": "export_revision_changed"
                if isinstance(exc, MCPOperationError) and exc.code == "export_revision_changed"
                else "export_unavailable",
                "message": "Inspect the current selection, fields and revision. Expired completed exports cannot be regenerated by retrying the same operation.",
            }
            if isinstance(exc, ArtifactError) and exc.status_code == 503:
                result = {
                    "error": "export_busy",
                    "message": "Export sources or generation capacity are busy. Resume the same operation ID later; keep its original retry key.",
                }
        except Exception:
            await session.rollback()
            outcome = "failed"
            result = {
                "error": "export_failed",
                "message": "Inspect the saved operation before retrying with its operation ID. A new retry key may create another intended export.",
            }
        claims = token.claims if token and token.claims else {}
        audit = await AuditLogRepository(session).record(
            action=f"mcp.tool.{name}",
            entity_type="mcp_operation",
            entity_id=str(operation_id) if operation_id else None,
            user_id=UUID(token.subject) if token and token.subject else None,
            result=outcome,
            metadata={"capability": "mcp:export", "connection_id": claims.get("grant_id")},
        )
        # The durable completion and its safe invocation audit become visible together.
        await session.commit()
        mark_invocation_audited()
        result.update(
            audit_id=str(audit.id),
            environment=settings.app_env,
            revision=settings.app_revision,
            observed_at=datetime.now(UTC).isoformat(),
            completeness="complete" if outcome == "success" else "unavailable",
        )
        if operation_id is not None:
            result.setdefault("operation_id", str(operation_id))
        return result


def register_rooming_export_tools(server: MCPServer, app: FastAPI, settings: Settings) -> None:
    definition = rooming_export_operation(settings, rooming_excel_support())
    app.state.mcp_operations[definition.policy.name] = definition

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=True, destructive_hint=False, idempotent_hint=True, open_world_hint=False
        ),
    )
    async def inspect_rooming_export(export: RoomingExportRequest) -> dict[str, Any]:
        """Inspect a current allocated hotel's rooming list or check-in workbook.

        Supply exact agency, group and hotel IDs and the intended workbook kind.
        This reads canonical allocation and existing check-in records. It does not
        allocate rooms, scan a QR code, check anybody in, or issue keys or letters.
        Missing/stale allocation or oversized input is rejected, never repaired.
        """
        return await _invoke_export(app, settings, name="inspect_rooming_export", request=export)

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    async def prepare_rooming_export(
        export: RoomingExportRequest,
        expected_revision: Annotated[str, Field(pattern=r"^[a-f0-9]{64}$")],
        idempotency_key: Annotated[str, Field(min_length=16, max_length=256)],
    ) -> dict[str, Any]:
        """Prepare the inspected hotel workbook using one stable retry key.

        A committed request receipt precedes generation. Retry the identical request
        with the same key after an uncertain response, or resume its operation ID.
        This writes a private expiring snapshot using the website workbook generator.
        Local delivery verifies size and checksum before acknowledging the copy.
        It never changes allocation, check-in evidence, passport history or messages.
        """
        receipt = await invoke_operation(
            app,
            settings,
            definition,
            idempotency_key=idempotency_key,
            payload={
                "export": export.model_dump(mode="json"),
                "expected_revision": expected_revision,
            },
        )
        if "receipt" not in receipt:
            return receipt
        operation_id = UUID(receipt["receipt"]["operation_id"])
        result = await _invoke_export(
            app, settings, name="generate_rooming_export", operation_id=operation_id
        )
        result["receipt"] = receipt["receipt"]
        return result

    @server.tool(
        meta={"capability": "mcp:export"},
        annotations=ToolAnnotations(
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
    )
    async def resume_rooming_export(operation_id: UUID) -> dict[str, Any]:
        """Resume one queued export or recover its unexpired completed artifact.

        Current actor, export capability, exact group and hotel association
        are revalidated. A new authorized connection receives its own protected
        locator to the same workbook. Expired results never regenerate.
        """
        return await _invoke_export(
            app, settings, name="resume_rooming_export", operation_id=operation_id
        )
