// Coordinates: OurAirports airports.csv, public domain, retrieved 2026-09-07.
// https://ourairports.com/data/ and https://davidmegginson.github.io/ourairports-data/airports.csv
// Snapshot SHA-256: 242f6fc43a1a2a8b04d75ddff8b4de03016d8fb5ae5fbcc2ed12ffae88103a21
// Points are representative airport locations for a destination illustration, not booked flights.
// Country-to-city choices and aliases are the explicit application policy, not source-data claims.
import type { GeoPoint } from './journey-route';

export type DestinationCatalogEntry = Readonly<{
  point: GeoPoint;
  aliases: readonly string[];
  countryAliases: readonly string[];
}>;

export const DESTINATION_CATALOG: readonly DestinationCatalogEntry[] = [
  {"point": {"city": "New Delhi","country": "India","countryCode": "IN","latitude": 28.55563,"longitude": 77.09519,"iata": "DEL"},"aliases": ["Delhi","NCR"],"countryAliases": ["India","IN","IND"]},
  {"point": {"city": "Mumbai","country": "India","countryCode": "IN","latitude": 19.088699,"longitude": 72.867897,"iata": "BOM"},"aliases": ["Bombay"],"countryAliases": []},
  {"point": {"city": "Bengaluru","country": "India","countryCode": "IN","latitude": 13.1979,"longitude": 77.706299,"iata": "BLR"},"aliases": ["Bangalore"],"countryAliases": []},
  {"point": {"city": "Chennai","country": "India","countryCode": "IN","latitude": 12.990005,"longitude": 80.169296,"iata": "MAA"},"aliases": ["Madras"],"countryAliases": []},
  {"point": {"city": "Hyderabad","country": "India","countryCode": "IN","latitude": 17.231318,"longitude": 78.429855,"iata": "HYD"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Kolkata","country": "India","countryCode": "IN","latitude": 22.654012,"longitude": 88.44765,"iata": "CCU"},"aliases": ["Calcutta"],"countryAliases": []},
  {"point": {"city": "Goa","country": "India","countryCode": "IN","latitude": 15.380062,"longitude": 73.833328,"iata": "GOI"},"aliases": ["Dabolim"],"countryAliases": []},
  {"point": {"city": "Jaipur","country": "India","countryCode": "IN","latitude": 26.8242,"longitude": 75.812202,"iata": "JAI"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Kochi","country": "India","countryCode": "IN","latitude": 10.151047,"longitude": 76.400838,"iata": "COK"},"aliases": ["Cochin"],"countryAliases": []},
  {"point": {"city": "Ahmedabad","country": "India","countryCode": "IN","latitude": 23.0772,"longitude": 72.634697,"iata": "AMD"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Singapore","country": "Singapore","countryCode": "SG","latitude": 1.35019,"longitude": 103.994003,"iata": "SIN"},"aliases": [],"countryAliases": ["Singapore","SG","SGP"]},
  {"point": {"city": "Dubai","country": "United Arab Emirates","countryCode": "AE","latitude": 25.24979,"longitude": 55.370992,"iata": "DXB"},"aliases": [],"countryAliases": ["United Arab Emirates","United Arab Emirates UAE","UAE","U.A.E.","AE","ARE","Emirates"]},
  {"point": {"city": "Abu Dhabi","country": "United Arab Emirates","countryCode": "AE","latitude": 24.440966,"longitude": 54.649237,"iata": "AUH"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Sharjah","country": "United Arab Emirates","countryCode": "AE","latitude": 25.3286,"longitude": 55.5172,"iata": "SHJ"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Sydney","country": "Australia","countryCode": "AU","latitude": -33.946098,"longitude": 151.177002,"iata": "SYD"},"aliases": [],"countryAliases": ["Australia","AU","AUS"]},
  {"point": {"city": "Melbourne","country": "Australia","countryCode": "AU","latitude": -37.670732,"longitude": 144.837898,"iata": "MEL"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Brisbane","country": "Australia","countryCode": "AU","latitude": -27.384199142456055,"longitude": 153.11700439453125,"iata": "BNE"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Perth","country": "Australia","countryCode": "AU","latitude": -31.94029998779297,"longitude": 115.96700286865234,"iata": "PER"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Cairns","country": "Australia","countryCode": "AU","latitude": -16.878921,"longitude": 145.74948,"iata": "CNS"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Gold Coast","country": "Australia","countryCode": "AU","latitude": -28.165962,"longitude": 153.506641,"iata": "OOL"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Auckland","country": "New Zealand","countryCode": "NZ","latitude": -37.01199,"longitude": 174.786331,"iata": "AKL"},"aliases": [],"countryAliases": ["New Zealand","NZ","NZL"]},
  {"point": {"city": "Queenstown","country": "New Zealand","countryCode": "NZ","latitude": -45.019205,"longitude": 168.746379,"iata": "ZQN"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Bangkok","country": "Thailand","countryCode": "TH","latitude": 13.6811,"longitude": 100.747002,"iata": "BKK"},"aliases": [],"countryAliases": ["Thailand","TH","THA"]},
  {"point": {"city": "Phuket","country": "Thailand","countryCode": "TH","latitude": 8.113257,"longitude": 98.3174,"iata": "HKT"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Ko Samui","country": "Thailand","countryCode": "TH","latitude": 9.54779,"longitude": 100.061996,"iata": "USM"},"aliases": ["Koh Samui"],"countryAliases": []},
  {"point": {"city": "Pattaya","country": "Thailand","countryCode": "TH","latitude": 12.6799,"longitude": 101.004997,"iata": "UTP"},"aliases": ["U-Tapao"],"countryAliases": []},
  {"point": {"city": "Kuala Lumpur","country": "Malaysia","countryCode": "MY","latitude": 2.74558,"longitude": 101.709999,"iata": "KUL"},"aliases": [],"countryAliases": ["Malaysia","MY","MYS"]},
  {"point": {"city": "Langkawi","country": "Malaysia","countryCode": "MY","latitude": 6.32973,"longitude": 99.728699,"iata": "LGK"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Denpasar","country": "Indonesia","countryCode": "ID","latitude": -8.748409,"longitude": 115.167123,"iata": "DPS"},"aliases": ["Bali"],"countryAliases": ["Indonesia","ID","IDN"]},
  {"point": {"city": "Jakarta","country": "Indonesia","countryCode": "ID","latitude": -6.12557,"longitude": 106.655998,"iata": "CGK"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Hanoi","country": "Vietnam","countryCode": "VN","latitude": 21.221201,"longitude": 105.806999,"iata": "HAN"},"aliases": [],"countryAliases": ["Vietnam","Viet Nam","VN","VNM"]},
  {"point": {"city": "Ho Chi Minh City","country": "Vietnam","countryCode": "VN","latitude": 10.8188,"longitude": 106.652,"iata": "SGN"},"aliases": ["Saigon","Ho Chi Minh"],"countryAliases": []},
  {"point": {"city": "Da Nang","country": "Vietnam","countryCode": "VN","latitude": 16.0439,"longitude": 108.198997,"iata": "DAD"},"aliases": ["Danang"],"countryAliases": []},
  {"point": {"city": "Malé","country": "Maldives","countryCode": "MV","latitude": 4.19183,"longitude": 73.529099,"iata": "MLE"},"aliases": ["Male"],"countryAliases": ["Maldives","MV","MDV"]},
  {"point": {"city": "Port Louis","country": "Mauritius","countryCode": "MU","latitude": -20.430201,"longitude": 57.683601,"iata": "MRU"},"aliases": [],"countryAliases": ["Mauritius","MU","MUS"]},
  {"point": {"city": "Victoria","country": "Seychelles","countryCode": "SC","latitude": -4.67434,"longitude": 55.521801,"iata": "SEZ"},"aliases": ["Mahe","Mahé"],"countryAliases": ["Seychelles","SC","SYC"]},
  {"point": {"city": "Colombo","country": "Sri Lanka","countryCode": "LK","latitude": 7.180759906768799,"longitude": 79.88410186767578,"iata": "CMB"},"aliases": [],"countryAliases": ["Sri Lanka","LK","LKA"]},
  {"point": {"city": "Kathmandu","country": "Nepal","countryCode": "NP","latitude": 27.6966,"longitude": 85.3591,"iata": "KTM"},"aliases": [],"countryAliases": ["Nepal","NP","NPL"]},
  {"point": {"city": "Paro","country": "Bhutan","countryCode": "BT","latitude": 27.4032,"longitude": 89.424599,"iata": "PBH"},"aliases": [],"countryAliases": ["Bhutan","BT","BTN"]},
  {"point": {"city": "Doha","country": "Qatar","countryCode": "QA","latitude": 25.273056,"longitude": 51.608056,"iata": "DOH"},"aliases": [],"countryAliases": ["Qatar","QA","QAT"]},
  {"point": {"city": "Muscat","country": "Oman","countryCode": "OM","latitude": 23.600218,"longitude": 58.285268,"iata": "MCT"},"aliases": [],"countryAliases": ["Oman","OM","OMN"]},
  {"point": {"city": "Manama","country": "Bahrain","countryCode": "BH","latitude": 26.267295,"longitude": 50.63764,"iata": "BAH"},"aliases": [],"countryAliases": ["Bahrain","BH","BHR"]},
  {"point": {"city": "Riyadh","country": "Saudi Arabia","countryCode": "SA","latitude": 24.9576,"longitude": 46.698799,"iata": "RUH"},"aliases": [],"countryAliases": ["Saudi Arabia","SA","SAU"]},
  {"point": {"city": "Jeddah","country": "Saudi Arabia","countryCode": "SA","latitude": 21.680241,"longitude": 39.157436,"iata": "JED"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Kuwait City","country": "Kuwait","countryCode": "KW","latitude": 29.224487,"longitude": 47.969813,"iata": "KWI"},"aliases": [],"countryAliases": ["Kuwait","KW","KWT"]},
  {"point": {"city": "Hong Kong","country": "Hong Kong","countryCode": "HK","latitude": 22.31184,"longitude": 113.914862,"iata": "HKG"},"aliases": [],"countryAliases": ["Hong Kong","HK","HKG"]},
  {"point": {"city": "Macau","country": "Macau","countryCode": "MO","latitude": 22.149599,"longitude": 113.592003,"iata": "MFM"},"aliases": ["Macao"],"countryAliases": ["Macau","Macao","MO","MAC"]},
  {"point": {"city": "Tokyo","country": "Japan","countryCode": "JP","latitude": 35.76858,"longitude": 140.388714,"iata": "NRT"},"aliases": ["Narita"],"countryAliases": ["Japan","JP","JPN"]},
  {"point": {"city": "Osaka","country": "Japan","countryCode": "JP","latitude": 34.427299,"longitude": 135.244003,"iata": "KIX"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Seoul","country": "South Korea","countryCode": "KR","latitude": 37.469101,"longitude": 126.450996,"iata": "ICN"},"aliases": [],"countryAliases": ["South Korea","Republic of Korea","KR","KOR"]},
  {"point": {"city": "Beijing","country": "China","countryCode": "CN","latitude": 40.077349,"longitude": 116.596702,"iata": "PEK"},"aliases": ["Peking"],"countryAliases": ["China","CN","CHN"]},
  {"point": {"city": "Shanghai","country": "China","countryCode": "CN","latitude": 31.1434,"longitude": 121.805,"iata": "PVG"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Taipei","country": "Taiwan","countryCode": "TW","latitude": 25.0777,"longitude": 121.233002,"iata": "TPE"},"aliases": [],"countryAliases": ["Taiwan","TW","TWN"]},
  {"point": {"city": "Manila","country": "Philippines","countryCode": "PH","latitude": 14.5086,"longitude": 121.019997,"iata": "MNL"},"aliases": [],"countryAliases": ["Philippines","The Philippines","PH","PHL"]},
  {"point": {"city": "Siem Reap","country": "Cambodia","countryCode": "KH","latitude": 13.36974,"longitude": 104.223831,"iata": "SAI"},"aliases": [],"countryAliases": ["Cambodia","KH","KHM"]},
  {"point": {"city": "Istanbul","country": "Türkiye","countryCode": "TR","latitude": 41.274874,"longitude": 28.732136,"iata": "IST"},"aliases": [],"countryAliases": ["Turkey","Turkiye","Türkiye","TR","TUR"]},
  {"point": {"city": "Antalya","country": "Türkiye","countryCode": "TR","latitude": 36.898701,"longitude": 30.800501,"iata": "AYT"},"aliases": [],"countryAliases": []},
  {"point": {"city": "London","country": "United Kingdom","countryCode": "GB","latitude": 51.470748,"longitude": -0.459909,"iata": "LHR"},"aliases": ["Heathrow"],"countryAliases": ["United Kingdom","UK","U.K.","Great Britain","Britain","England","GB","GBR"]},
  {"point": {"city": "Edinburgh","country": "United Kingdom","countryCode": "GB","latitude": 55.950145,"longitude": -3.372288,"iata": "EDI"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Paris","country": "France","countryCode": "FR","latitude": 49.00896,"longitude": 2.554117,"iata": "CDG"},"aliases": [],"countryAliases": ["France","FR","FRA"]},
  {"point": {"city": "Nice","country": "France","countryCode": "FR","latitude": 43.658401,"longitude": 7.21587,"iata": "NCE"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Zurich","country": "Switzerland","countryCode": "CH","latitude": 47.458056,"longitude": 8.548056,"iata": "ZRH"},"aliases": ["Zürich"],"countryAliases": ["Switzerland","CH","CHE"]},
  {"point": {"city": "Geneva","country": "Switzerland","countryCode": "CH","latitude": 46.238098,"longitude": 6.10895,"iata": "GVA"},"aliases": ["Genève"],"countryAliases": []},
  {"point": {"city": "Rome","country": "Italy","countryCode": "IT","latitude": 41.804532,"longitude": 12.251998,"iata": "FCO"},"aliases": ["Roma"],"countryAliases": ["Italy","IT","ITA"]},
  {"point": {"city": "Milan","country": "Italy","countryCode": "IT","latitude": 45.6306,"longitude": 8.72811,"iata": "MXP"},"aliases": ["Milano"],"countryAliases": []},
  {"point": {"city": "Venice","country": "Italy","countryCode": "IT","latitude": 45.505299,"longitude": 12.3519,"iata": "VCE"},"aliases": ["Venezia"],"countryAliases": []},
  {"point": {"city": "Madrid","country": "Spain","countryCode": "ES","latitude": 40.493407,"longitude": -3.572249,"iata": "MAD"},"aliases": [],"countryAliases": ["Spain","España","ES","ESP"]},
  {"point": {"city": "Barcelona","country": "Spain","countryCode": "ES","latitude": 41.2971,"longitude": 2.07846,"iata": "BCN"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Amsterdam","country": "Netherlands","countryCode": "NL","latitude": 52.308601,"longitude": 4.76389,"iata": "AMS"},"aliases": [],"countryAliases": ["Netherlands","The Netherlands","Holland","NL","NLD"]},
  {"point": {"city": "Frankfurt","country": "Germany","countryCode": "DE","latitude": 50.026706,"longitude": 8.55835,"iata": "FRA"},"aliases": ["Frankfurt am Main"],"countryAliases": ["Germany","DE","DEU"]},
  {"point": {"city": "Munich","country": "Germany","countryCode": "DE","latitude": 48.353802,"longitude": 11.7861,"iata": "MUC"},"aliases": ["München","Munchen"],"countryAliases": []},
  {"point": {"city": "Berlin","country": "Germany","countryCode": "DE","latitude": 52.361738,"longitude": 13.502341,"iata": "BER"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Vienna","country": "Austria","countryCode": "AT","latitude": 48.110298,"longitude": 16.5697,"iata": "VIE"},"aliases": ["Wien"],"countryAliases": ["Austria","AT","AUT"]},
  {"point": {"city": "Prague","country": "Czechia","countryCode": "CZ","latitude": 50.100874,"longitude": 14.259911,"iata": "PRG"},"aliases": ["Praha"],"countryAliases": ["Czechia","Czech Republic","CZ","CZE"]},
  {"point": {"city": "Budapest","country": "Hungary","countryCode": "HU","latitude": 47.43018,"longitude": 19.262393,"iata": "BUD"},"aliases": [],"countryAliases": ["Hungary","HU","HUN"]},
  {"point": {"city": "Athens","country": "Greece","countryCode": "GR","latitude": 37.936401,"longitude": 23.9445,"iata": "ATH"},"aliases": [],"countryAliases": ["Greece","GR","GRC"]},
  {"point": {"city": "Lisbon","country": "Portugal","countryCode": "PT","latitude": 38.7813,"longitude": -9.13592,"iata": "LIS"},"aliases": ["Lisboa"],"countryAliases": ["Portugal","PT","PRT"]},
  {"point": {"city": "Dublin","country": "Ireland","countryCode": "IE","latitude": 53.428713,"longitude": -6.262121,"iata": "DUB"},"aliases": [],"countryAliases": ["Ireland","IE","IRL"]},
  {"point": {"city": "Copenhagen","country": "Denmark","countryCode": "DK","latitude": 55.617900848389,"longitude": 12.656000137329,"iata": "CPH"},"aliases": [],"countryAliases": ["Denmark","DK","DNK"]},
  {"point": {"city": "Stockholm","country": "Sweden","countryCode": "SE","latitude": 59.64849,"longitude": 17.928829,"iata": "ARN"},"aliases": [],"countryAliases": ["Sweden","SE","SWE"]},
  {"point": {"city": "Oslo","country": "Norway","countryCode": "NO","latitude": 60.193901,"longitude": 11.1004,"iata": "OSL"},"aliases": [],"countryAliases": ["Norway","NO","NOR"]},
  {"point": {"city": "Helsinki","country": "Finland","countryCode": "FI","latitude": 60.318363,"longitude": 24.963341,"iata": "HEL"},"aliases": [],"countryAliases": ["Finland","FI","FIN"]},
  {"point": {"city": "Warsaw","country": "Poland","countryCode": "PL","latitude": 52.165699,"longitude": 20.9671,"iata": "WAW"},"aliases": [],"countryAliases": ["Poland","PL","POL"]},
  {"point": {"city": "Reykjavík","country": "Iceland","countryCode": "IS","latitude": 63.985001,"longitude": -22.6056,"iata": "KEF"},"aliases": ["Reykjavik","Keflavik"],"countryAliases": ["Iceland","IS","ISL"]},
  {"point": {"city": "New York","country": "United States","countryCode": "US","latitude": 40.639447,"longitude": -73.779317,"iata": "JFK"},"aliases": ["New York City","NYC"],"countryAliases": ["United States","United States of America","USA","U.S.A.","US","U.S.","America"]},
  {"point": {"city": "Los Angeles","country": "United States","countryCode": "US","latitude": 33.942501,"longitude": -118.407997,"iata": "LAX"},"aliases": ["LA"],"countryAliases": []},
  {"point": {"city": "Las Vegas","country": "United States","countryCode": "US","latitude": 36.083361,"longitude": -115.151817,"iata": "LAS"},"aliases": [],"countryAliases": []},
  {"point": {"city": "San Francisco","country": "United States","countryCode": "US","latitude": 37.619806,"longitude": -122.374821,"iata": "SFO"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Orlando","country": "United States","countryCode": "US","latitude": 28.429399490356445,"longitude": -81.30899810791016,"iata": "MCO"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Toronto","country": "Canada","countryCode": "CA","latitude": 43.675935,"longitude": -79.629421,"iata": "YYZ"},"aliases": [],"countryAliases": ["Canada","CA","CAN"]},
  {"point": {"city": "Vancouver","country": "Canada","countryCode": "CA","latitude": 49.193901,"longitude": -123.183998,"iata": "YVR"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Cairo","country": "Egypt","countryCode": "EG","latitude": 30.111534,"longitude": 31.396694,"iata": "CAI"},"aliases": [],"countryAliases": ["Egypt","EG","EGY"]},
  {"point": {"city": "Johannesburg","country": "South Africa","countryCode": "ZA","latitude": -26.140081,"longitude": 28.246801,"iata": "JNB"},"aliases": ["Joburg"],"countryAliases": ["South Africa","ZA","ZAF"]},
  {"point": {"city": "Cape Town","country": "South Africa","countryCode": "ZA","latitude": -33.97403,"longitude": 18.604333,"iata": "CPT"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Nairobi","country": "Kenya","countryCode": "KE","latitude": -1.318886,"longitude": 36.928233,"iata": "NBO"},"aliases": [],"countryAliases": ["Kenya","KE","KEN"]},
  {"point": {"city": "Marrakesh","country": "Morocco","countryCode": "MA","latitude": 31.604807,"longitude": -8.035788,"iata": "RAK"},"aliases": ["Marrakech"],"countryAliases": ["Morocco","MA","MAR"]},
  {"point": {"city": "Casablanca","country": "Morocco","countryCode": "MA","latitude": 33.3675,"longitude": -7.58997,"iata": "CMN"},"aliases": [],"countryAliases": []},
  {"point": {"city": "São Paulo","country": "Brazil","countryCode": "BR","latitude": -23.431274,"longitude": -46.469954,"iata": "GRU"},"aliases": ["Sao Paulo"],"countryAliases": ["Brazil","Brasil","BR","BRA"]},
  {"point": {"city": "Rio de Janeiro","country": "Brazil","countryCode": "BR","latitude": -22.809999,"longitude": -43.250557,"iata": "GIG"},"aliases": [],"countryAliases": []},
  {"point": {"city": "Buenos Aires","country": "Argentina","countryCode": "AR","latitude": -34.8222,"longitude": -58.5358,"iata": "EZE"},"aliases": [],"countryAliases": ["Argentina","AR","ARG"]},
  {"point": {"city": "Mexico City","country": "Mexico","countryCode": "MX","latitude": 19.435822,"longitude": -99.07033,"iata": "MEX"},"aliases": [],"countryAliases": ["Mexico","México","MX","MEX"]},
  {"point": {"city": "Baku","country": "Azerbaijan","countryCode": "AZ","latitude": 40.47278,"longitude": 50.050931,"iata": "GYD"},"aliases": [],"countryAliases": ["Azerbaijan","AZ","AZE"]},
  {"point": {"city": "Tbilisi","country": "Georgia","countryCode": "GE","latitude": 41.669201,"longitude": 44.9547,"iata": "TBS"},"aliases": [],"countryAliases": ["Georgia","GE","GEO"]},
  {"point": {"city": "Yerevan","country": "Armenia","countryCode": "AM","latitude": 40.148941,"longitude": 44.397887,"iata": "EVN"},"aliases": [],"countryAliases": ["Armenia","AM","ARM"]},
  {"point": {"city": "Almaty","country": "Kazakhstan","countryCode": "KZ","latitude": 43.354267,"longitude": 77.042828,"iata": "ALA"},"aliases": [],"countryAliases": ["Kazakhstan","KZ","KAZ"]},
  {"point": {"city": "Tashkent","country": "Uzbekistan","countryCode": "UZ","latitude": 41.2579,"longitude": 69.281197,"iata": "TAS"},"aliases": [],"countryAliases": ["Uzbekistan","UZ","UZB"]},
];
