events {
    worker_connections 128;
}

http {
    access_log off;
    server_tokens off;

    upstream coordinator_frontend {
        server passdetection-frontend:3000;
        keepalive 8;
    }

    upstream coordinator_backend {
        server passdetection-backend:8000;
        keepalive 8;
    }

    server {
        listen 8080;

        location /api/ {
            proxy_pass http://coordinator_backend;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto http;
        }

        location / {
            proxy_pass http://coordinator_frontend;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto http;
        }
    }
}
