"""Exercise only uniquely named synthetic credentials in the real Windows vault."""

import asyncio
import os
import sys
import time
import uuid
from pathlib import Path

import pytest

from gc_mcp_connector.vault import Credential, WindowsCredentialLock, WindowsVault

pytestmark = pytest.mark.skipif(sys.platform != "win32", reason="native Windows qualification")


def child_environment():
    return {**os.environ, "PYTHONPATH": str(Path(__file__).resolve().parents[1] / "src")}


async def test_native_vault_round_trip_survives_a_process_boundary():
    key = "GlobalConnects-MCP-qualification-" + uuid.uuid4().hex
    vault = WindowsVault(key)
    assert vault.read() is None
    credential = Credential("synthetic-vault-test-only-" + "x" * 32, time.time() + 600)
    try:
        vault.write(credential)
        assert vault.read() == credential
        child = await asyncio.create_subprocess_exec(
            sys.executable,
            "-c",
            """
import sys
from gc_mcp_connector.vault import WindowsVault
credential = WindowsVault(sys.argv[1]).read()
assert credential and credential.refresh_token == 'synthetic-vault-test-only-' + 'x' * 32
print('synthetic credential recovered')
""",
            key,
            env=child_environment(),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await asyncio.wait_for(child.communicate(), 10)
        assert child.returncode == 0, stderr.decode(errors="replace")
        assert stdout.strip() == b"synthetic credential recovered"
    finally:
        # This target was generated by this test and confirmed absent above.
        vault.delete()
    assert vault.read() is None


async def test_native_rotation_mutex_blocks_other_process_until_owner_releases():
    key = "GlobalConnects-MCP-qualification-" + uuid.uuid4().hex
    child = None
    try:
        async with WindowsCredentialLock(key)():
            child = await asyncio.create_subprocess_exec(
                sys.executable,
                "-u",
                "-c",
                """
import asyncio, sys
from gc_mcp_connector.vault import WindowsCredentialLock
async def main():
    print('waiting', flush=True)
    async with WindowsCredentialLock(sys.argv[1])():
        print('acquired', flush=True)
asyncio.run(main())
""",
                key,
                env=child_environment(),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            assert await asyncio.wait_for(child.stdout.readline(), 10) == b"waiting\r\n"
            acquired = asyncio.create_task(child.stdout.readline())
            await asyncio.sleep(0.15)
            assert not acquired.done(), "Another process crossed the held native credential lock"
        assert (await asyncio.wait_for(acquired, 10)).strip() == b"acquired"
        await asyncio.wait_for(child.wait(), 10)
        assert child.returncode == 0
    finally:
        if child is not None and child.returncode is None:
            child.kill()
            await child.wait()
