"""Bounded deterministic PNG fixtures containing no people or biometric data."""

from __future__ import annotations

import hashlib
import struct
import zlib
from functools import lru_cache
from typing import Literal

SyntheticVariant = Literal["thumbnail", "preview", "analysis", "optimized", "original"]

# These are deliberately compact passive placeholders. The 5,000-asset fixture
# carries realistic high-resolution dimensions and byte-shape metadata in the
# database; materialising thousands of megapixel PNGs merely to calculate
# deterministic development checksums would turn fixture bootstrap into an
# unbounded CPU/memory benchmark. Provider and delivery contract tests still
# validate exact size/checksum equality against these generated bytes.
_DIMENSIONS: dict[SyntheticVariant, tuple[int, int]] = {
    "thumbnail": (48, 36),
    "preview": (64, 48),
    "analysis": (96, 72),
    "optimized": (80, 60),
    "original": (96, 72),
}


def synthetic_media_dimensions(variant: SyntheticVariant) -> tuple[int, int]:
    return _DIMENSIONS[variant]


@lru_cache(maxsize=24)
def synthetic_png(asset_key: str, variant: SyntheticVariant) -> bytes:
    """Create a valid, passive RGB PNG without file or network I/O."""

    if not asset_key or len(asset_key) > 128:
        raise ValueError("Synthetic media asset key must be bounded")
    width, height = _DIMENSIONS[variant]
    seed = hashlib.sha256(f"{asset_key}|{variant}".encode("utf-8")).digest()
    rows = bytearray()
    for y in range(height):
        rows.append(0)  # PNG filter type: None.
        red = (seed[0] + y // 8) % 256
        green = (seed[1] + y // 5) % 256
        blue = (seed[2] + y // 3) % 256
        row = bytes((red, green, blue)) * width
        rows.extend(row)
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + _chunk(b"IHDR", header)
        + _chunk(b"IDAT", zlib.compress(bytes(rows), level=9))
        + _chunk(b"IEND", b"")
    )


def synthetic_media_checksum(asset_key: str, variant: SyntheticVariant) -> tuple[int, str]:
    content = synthetic_png(asset_key, variant)
    return len(content), hashlib.sha256(content).hexdigest()


def _chunk(kind: bytes, payload: bytes) -> bytes:
    body = kind + payload
    return struct.pack(">I", len(payload)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)
