import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import test from 'node:test';

const require = createRequire(import.meta.url);
const plugin = require('../plugins/with-android-release-signing');

const GENERATED_GRADLE_FIXTURE = `apply plugin: "com.android.application"

android {
    namespace 'com.example.app'
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Expo's generated release fallback must not survive.
            signingConfig signingConfigs.debug
            minifyEnabled true
        }
    }
}
`;

test('release signing transform is idempotent and removes the debug fallback', () => {
  const patched = plugin.patchAppBuildGradle(GENERATED_GRADLE_FIXTURE);

  assert.equal(plugin.patchAppBuildGradle(patched), patched);
  assert.match(patched, /System\.getenv\(variableName\)/);
  assert.match(patched, /signingConfig signingConfigs\.release/);
  assert.match(patched, /signingConfig null/);
  assert.match(patched, /taskName\.startsWith\('assemble'\)/);
  assert.match(patched, /taskName\.startsWith\('bundle'\)/);
  assert.match(patched, /Android release signing is required/);

  const debugBindings = patched.match(/signingConfig signingConfigs\.debug/g) ?? [];
  assert.equal(debugBindings.length, 1, 'only the debug build type may use the debug key');
});

test('credentials remain Gradle environment references and are never captured by the transform', () => {
  const sentinels = [
    'DO_NOT_CAPTURE_KEYSTORE_PATH',
    'DO_NOT_CAPTURE_STORE_PASSWORD',
    'DO_NOT_CAPTURE_ALIAS',
    'DO_NOT_CAPTURE_KEY_PASSWORD',
  ];
  const names = [
    'GC_ANDROID_KEYSTORE_FILE',
    'GC_ANDROID_KEYSTORE_PASSWORD',
    'GC_ANDROID_KEY_ALIAS',
    'GC_ANDROID_KEY_PASSWORD',
  ];
  const previous = new Map(names.map((name) => [name, process.env[name]]));
  names.forEach((name, index) => { process.env[name] = sentinels[index]; });

  try {
    const patched = plugin.patchAppBuildGradle(GENERATED_GRADLE_FIXTURE);
    for (const name of names) assert.match(patched, new RegExp(name));
    for (const sentinel of sentinels) assert.doesNotMatch(patched, new RegExp(sentinel));
    assert.match(patched, /gcReleaseSigningPresentCount > 0/);
    assert.match(patched, /partially configured/);
    assert.doesNotMatch(patched, /println|logger\.|System\.out/);
  } finally {
    for (const [name, value] of previous) {
      if (value === undefined) delete process.env[name];
      else process.env[name] = value;
    }
  }
});

test('template drift and damaged markers fail closed', () => {
  assert.throws(
    () => plugin.patchAppBuildGradle(
      GENERATED_GRADLE_FIXTURE.replace(
        'signingConfig signingConfigs.debug\n            minifyEnabled true',
        'minifyEnabled true',
      ),
    ),
    /debug signing fallback/,
  );

  assert.throws(
    () => plugin.patchAppBuildGradle(
      `${GENERATED_GRADLE_FIXTURE}\n// @generated by with-android-release-signing: declarations`,
    ),
    /incomplete or duplicate generated Gradle markers/,
  );
});
