"""Passport API limits and established export/import helper names."""

from app.presentation.api.v1.routes import passport_excel_import_support as _excel_support
from app.presentation.api.v1.routes import passport_export_support as _export_support

PASSPORT_EXCEL_UPLOAD_READ_CHUNK_BYTES = 1024 * 1024
PASSPORT_DELETE_INLINE_CLEANUP_MAX_OBJECTS = 500
PASSPORT_BULK_SELECTION_MAX = 1_500
SELECTED_PASSPORT_IMAGE_EXPORT_MAX_BYTES = 512 * 1024 * 1024
PASSPORT_COMBINED_EXPORT_MAX_ROWS = 1500
_PassportExcelExistingIndexes = _excel_support._PassportExcelExistingIndexes
_PassportExcelImportConflict = _excel_support._PassportExcelImportConflict
_apply_passport_excel_row_to_submission = _excel_support._apply_passport_excel_row_to_submission
_build_passport_excel_existing_indexes = _excel_support._build_passport_excel_existing_indexes
_canonical_excel_passport_number = _excel_support._canonical_excel_passport_number
_canonical_excel_staff_code = _excel_support._canonical_excel_staff_code
_deduplicate_passport_excel_rows = _excel_support._deduplicate_passport_excel_rows
_excel_identity_key = _excel_support._excel_identity_key
_excel_scalar_text = _excel_support._excel_scalar_text
_merge_excel_fields = _excel_support._merge_excel_fields
_normalized_excel_mapping_items = _excel_support._normalized_excel_mapping_items
_passport_excel_row_fingerprint = _excel_support._passport_excel_row_fingerprint
_passport_number_for_import_row = _excel_support._passport_number_for_import_row
_preferred_submission_value = _excel_support._preferred_submission_value
_resolve_existing_passport_excel_submission = (
    _excel_support._resolve_existing_passport_excel_submission
)
_same_passport_submission = _excel_support._same_passport_submission
_staff_code_for_import_row = _excel_support._staff_code_for_import_row
_staff_code_for_submission = _excel_support._staff_code_for_submission
_strict_passport_number_for_submission = _excel_support._strict_passport_number_for_submission
_strict_staff_code_for_submission = _excel_support._strict_staff_code_for_submission
_AGENCY_MATCH_SIMILARITY_THRESHOLD = _export_support._AGENCY_MATCH_SIMILARITY_THRESHOLD
_FIXED_IMPORTED_EXPORT_KEYS = _export_support._FIXED_IMPORTED_EXPORT_KEYS
_WHATSAPP_EMAIL_IMPORTED_KEYS = _export_support._WHATSAPP_EMAIL_IMPORTED_KEYS
_WHATSAPP_PHONE_IMPORTED_KEYS = _export_support._WHATSAPP_PHONE_IMPORTED_KEYS
_WHATSAPP_SOURCE_METADATA_KEYS = _export_support._WHATSAPP_SOURCE_METADATA_KEYS
_ZONE_IMPORTED_KEYS = _export_support._ZONE_IMPORTED_KEYS
_AgencyExportMatches = _export_support._AgencyExportMatches
_agency_match_export_field = _export_support._agency_match_export_field
_agency_match_similarity = _export_support._agency_match_similarity
_apply_agency_export_matches = _export_support._apply_agency_export_matches
_apply_pending_export_fields = _export_support._apply_pending_export_fields
_combined_export_field_catalog = _export_support._combined_export_field_catalog
_export_additional_values = _export_support._export_additional_values
_export_agency_match_field_catalog = _export_support._export_agency_match_field_catalog
_export_agency_matches = _export_support._export_agency_matches
_export_effective_whatsapp_matches = _export_support._export_effective_whatsapp_matches
_export_field_catalog = _export_support._export_field_catalog
_export_group_details = _export_support._export_group_details
_export_whatsapp_contacts = _export_support._export_whatsapp_contacts
_export_whatsapp_match_rows = _export_support._export_whatsapp_match_rows
_export_zone_names = _export_support._export_zone_names
_export_zone_names_from_match_rows = _export_support._export_zone_names_from_match_rows
_group_export_details = _export_support._group_export_details
_imported_zone_name = _export_support._imported_zone_name
_international_airport_is_enabled = _export_support._international_airport_is_enabled
_merge_export_field_catalogs = _export_support._merge_export_field_catalogs
_normalized_agency_match_value = _export_support._normalized_agency_match_value
_normalized_imported_field_key = _export_support._normalized_imported_field_key
_pending_recipient_export_rows = _export_support._pending_recipient_export_rows
_recipient_export_value = _export_support._recipient_export_value
_recipient_old_given_name = _export_support._recipient_old_given_name
_select_whatsapp_tracking_export_payload = _export_support._select_whatsapp_tracking_export_payload
_stored_resolution_uuid_list = _export_support._stored_resolution_uuid_list
_submission_agency_dealership_name = _export_support._submission_agency_dealership_name
_whatsapp_tracking_export_rows = _export_support._whatsapp_tracking_export_rows
_export_people_snapshot = _export_support._export_people_snapshot
_validated_export_history_ids = _export_support._validated_export_history_ids
_validated_export_history_people = _export_support._validated_export_history_people
_validated_export_kind = _export_support._validated_export_kind
_validated_export_mode = _export_support._validated_export_mode
